#place the information of the user as input, in this case the worked hours 
xh = input("enter hours: ")
# now input for the rate
xr = input("enter rate: ")
# in this particular case, I have to use float funtion due to an error generated by python
xp = float(xh) * float(xr)
#final result it would be print: Pay plus the xp result.
print("Pay",xp)
#running good so far.

